### ISSUE TITLE
Omeka S encountered an error

### ISSUE THREAD

**Issue by hajoki** [biblibre/omeka-s-module-ItemSetsTree#1]
Hello,
I am using Linux Mint 17, based on Ubuntu 14.04.5 LTS, and Apache 2, PHP 7.0.16, I got the following error when installing the module ItemSetsTree for Omeka S:
```
There was an error.
Error: Call to undefined function ItemSetsTree\xdebug_break() in /var/www/html/omeka-s2/modules/ItemSetsTree/Module.php:71
Stack trace:
#0 /var/www/html/omeka-s2/application/src/Module/Manager.php(232): ItemSetsTree\Module->install(Object(Zend\ServiceManager\ServiceManager))
#1 /var/www/html/omeka-s2/application/src/Controller/Admin/ModuleController.php(116): Omeka\Module\Manager->install(Object(Omeka\Module\Module))
#2 /var/www/html/omeka-s2/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\ModuleController->installAction()
#3 /var/www/html/omeka-s2/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /var/www/html/omeka-s2/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#5 /var/www/html/omeka-s2/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#6 /var/www/html/omeka-s2/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#7 /var/www/html/omeka-s2/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /var/www/html/omeka-s2/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/html/omeka-s2/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#10 /var/www/html/omeka-s2/index.php(17): Zend\Mvc\Application->run()
#11 {main}
```
When commenting the two lines containing xdebug in Module.php, I got the following error:

```
Omeka S encountered an error

Zend\ServiceManager\Exception\ServiceNotCreatedException
Service with name "Omeka\Acl" could not be created. Reason: File mapping drivers must have a valid directory path, however the given path [/var/www/html/omeka-s2/modules/ItemSetsTree/src/Entity] seems to be incorrect!

Details:

Doctrine\Common\Persistence\Mapping\MappingException: File mapping drivers must have a valid directory path, however the given path [/var/www/html/omeka-s2/modules/ItemSetsTree/src/Entity] seems to be incorrect! in /var/www/html/omeka-s2/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:61
Stack trace:
#0 /var/www/html/omeka-s2/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/AnnotationDriver.php(208): Doctrine\Common\Persistence\Mapping\MappingException::fileMappingDriversRequireConfiguredDirectoryPath('[/var/www/html/...')
#1 /var/www/html/omeka-s2/application/src/Service/AclFactory.php(103): Doctrine\Common\Persistence\Mapping\Driver\AnnotationDriver->getAllClassNames()
#2 /var/www/html/omeka-s2/application/src/Service/AclFactory.php(34): Omeka\Service\AclFactory->addResources(Object(Omeka\Permissions\Acl), Object(Zend\ServiceManager\ServiceManager))
#3 /var/www/html/omeka-s2/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(747): Omeka\Service\AclFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'Omeka\\Acl', NULL)
#4 /var/www/html/omeka-s2/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(195): Zend\ServiceManager\ServiceManager->doCreate('Omeka\\Acl')
#5 /var/www/html/omeka-s2/modules/Mapping/Module.php(28): Zend\ServiceManager\ServiceManager->get('Omeka\\Acl')
#6 /var/www/html/omeka-s2/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Mapping\Module->onBootstrap(Object(Zend\Mvc\MvcEvent))
#7 /var/www/html/omeka-s2/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#8 /var/www/html/omeka-s2/vendor/zendframework/zend-mvc/src/Application.php(161): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#9 /var/www/html/omeka-s2/application/src/Mvc/Application.php(40): Zend\Mvc\Application->bootstrap(Array)
#10 /var/www/html/omeka-s2/index.php(17): Omeka\Mvc\Application::init(Array)
#11 {main}

Next Zend\ServiceManager\Exception\ServiceNotCreatedException: Service with name "Omeka\Acl" could not be created. Reason: File mapping drivers must have a valid directory path, however the given path [/var/www/html/omeka-s2/modules/ItemSetsTree/src/Entity] seems to be incorrect! in /var/www/html/omeka-s2/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:754
Stack trace:
#0 /var/www/html/omeka-s2/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(195): Zend\ServiceManager\ServiceManager->doCreate('Omeka\\Acl')
#1 /var/www/html/omeka-s2/modules/Mapping/Module.php(28): Zend\ServiceManager\ServiceManager->get('Omeka\\Acl')
#2 /var/www/html/omeka-s2/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Mapping\Module->onBootstrap(Object(Zend\Mvc\MvcEvent))
#3 /var/www/html/omeka-s2/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#4 /var/www/html/omeka-s2/vendor/zendframework/zend-mvc/src/Application.php(161): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#5 /var/www/html/omeka-s2/application/src/Mvc/Application.php(40): Zend\Mvc\Application->bootstrap(Array)
#6 /var/www/html/omeka-s2/index.php(17): Omeka\Mvc\Application::init(Array)
#7 {main}
```

**Comment by jajm** [comment]
Hi,

Sorry but, as you have noticed, this module is not finished and is not working at all...
We do not plan to work on it for the moment. I will add a readme file to make that clear.

**Comment by hajoki** [comment]
Hello,
Oh ok, sorry and good idea if you can make the info clearer, I did not suspect the module was not ready yet as you are registered on this list:
https://daniel-km.github.io/UpgradeToOmekaS/
Thank you and good luck!

**Comment by jajm** [comment]
I wasn't aware of this list, thank you for pointing it out.
I submitted a pull request to remove this module from the list
