### ISSUE TITLE
Call to a member function getReference() on null 

### ISSUE THREAD

**Issue by sinanatra** [biblibre/omeka-s-module-ItemSetsTree#13]
On version `0.6.0` and Omeka version `3.2.1` whenever i try to access the item_sets_tree_edges endpoint i get a 500 and this message in the log:
```
Error: Call to a member function getReference() on null in /home/project/omeka-s/modules/ItemSetsTree/src/Api/Representation/ItemSetsTreeEdgeRepresentation.php:37
Stack trace:
#0 /home/project/omeka-s/application/src/Api/Representation/AbstractResourceRepresentation.php(75): ItemSetsTree\Api\Representation\ItemSetsTreeEdgeRepresentation->getJsonLd()
#1 [internal function]: Omeka\Api\Representation\AbstractResourceRepresentation->jsonSerialize()
#2 /home/project/omeka-s/vendor/laminas/laminas-json/src/Json.php(360): json_encode()
#3 /home/project/omeka-s/vendor/laminas/laminas-json/src/Json.php(325): Laminas\Json\Json::encodeViaPhpBuiltIn()
#4 /home/project/omeka-s/vendor/laminas/laminas-json/src/Json.php(98): Laminas\Json\Json::encodeValue()
#5 /home/project/omeka-s/vendor/laminas/laminas-view/src/Renderer/JsonRenderer.php(150): Laminas\Json\Json::encode()
#6 /home/project/omeka-s/application/src/View/Renderer/ApiJsonRenderer.php(54): Laminas\View\Renderer\JsonRenderer->render()
#7 /home/project/omeka-s/vendor/laminas/laminas-view/src/View.php(206): Omeka\View\Renderer\ApiJsonRenderer->render()
#8 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render()
#9 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render()
#10 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners()
#11 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent()
#12 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest()
#13 /home/project/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#14 {main}
```

**Comment by jajm** [comment]
Thanks for reporting the bug. It will be fixed in the next release

**Comment by sinanatra** [comment]
```
'o:parent_item_set' => $parentItemSet ? $parentItemSet->getReference() : null,
```

at `ItemSetsTreeEdgeRepresentation.php` solves the issue
